# This error tag corresponds to syslog messages notifying that the configured
# bgp neighbor has changed state
messages:
  # 'error' should be unique and vendor agnostic. Currently we are using the JUNOS syslog message name as the canonical name.
  # This may change if we are able to find a more well defined naming system.
  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from Idle to Connect (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: CONNECT
        bgp//neighbors//neighbor//{peer}//state//session-state-old: IDLE

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from Connect to Idle (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: IDLE
        bgp//neighbors//neighbor//{peer}//state//session-state-old: CONNECT

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from Connect to Active (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: ACTIVE
        bgp//neighbors//neighbor//{peer}//state//session-state-old: CONNECT

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from Active to Connect (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: CONNECT
        bgp//neighbors//neighbor//{peer}//state//session-state-old: ACTIVE

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from Connect to OpenSent (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: OPEN_SENT
        bgp//neighbors//neighbor//{peer}//state//session-state-old: CONNECT

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from Active to OpenSent (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: OPEN_SENT
        bgp//neighbors//neighbor//{peer}//state//session-state-old: ACTIVE

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from OpenSent to OpenConfirm (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: OPEN_CONFIRM
        bgp//neighbors//neighbor//{peer}//state//session-state-old: OPEN_SENT

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from OpenConfirm to Established (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: ESTABLISHED
        bgp//neighbors//neighbor//{peer}//state//session-state-old: OPEN_CONFIRM

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from Established to Idle (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: IDLE
        bgp//neighbors//neighbor//{peer}//state//session-state-old: ESTABLISHED

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from OpenConfirm to Idle (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: IDLE
        bgp//neighbors//neighbor//{peer}//state//session-state-old: OPEN_CONFIRM

  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from OpenSent to Idle (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: IDLE
        bgp//neighbors//neighbor//{peer}//state//session-state-old: OPEN_SENT


  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: RPD_BGP_NEIGHBOR_STATE_CHANGED
    values:
      peer: ([\w\d:\.]+)
      asn: (\d+)
      peeringType: (\w+)
      event: (\w+)
    line: 'BGP peer {peer} ({peeringType} AS {asn}) changed state from Active to Idle (event {event}) (instance master)'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//peer_as: asn
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: event
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: IDLE
        bgp//neighbors//neighbor//{peer}//state//session-state-old: ACTIVE
