language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install tox-travis
  - pip install coveralls
env:
  global:
    - secure: "aayKlfqIU/usydWSBz9FQnDWkzH6k4Uoz/aQmEDDB6ziSB9Y7AkszZKJ112aCGN2Zxqde0JTRIPQkAtniH8r1ZPvcoG+4ew31/cz8wolBE9OZs+wSsoWis57EwC/N/xjngvji5ENd3scRULOZciS8KUlqchRzAfcCM+sxPROJ38a3n2oA63IvSVMzbrSGyE2MukxE+bOyXeKtM9upyOC6nGEjcyb7nOdTQz8UcRzxnIIed4W9WpZqhK5gUbmZMlZSpXhu8upgXdrkooDgVLcpH65OaDfRMtExuTEV2CRxWPZLghxNaDgGVui9VbX9nUxOIe8nLwT0FpDr/fiDGn1StBBoy/6XbAbkWsy3PhLRNvXN9dvhKunCmjGs6W2qT6Ems0HmePrHJx2mtI/dGPQAxknDHY6YjMSqtMfbrOJFOerqQ6UI6YmYiBOMfgC36thIa11Pr6VFtGFtn12XTFw3ZmbBIrQ/EB7YtHAvK6w8oX1+Q//UJjTR9Vs8ZPZPcq376WxaNkc15EvHbQ28ZZOjtRyCDz8+0gNcBgx+EY9nt/1lWcLZ/wHLSFjGJtCMZhnfdE7IsJHnG31SpnumweSdQG4/Ngeo1fQYIXTX6eOt7hOJvkRCuzRJTxDQbD9KYXYs3ZmJYuAxVVlV25fmTaniHj6O5llbNwX5vvaYO6/YRY="
    - secure: "T5Kbh4QRvETRSaRKVjeu6Tap8TLvtePHaxerJM9ZQn0mH5c+LLjbQvWhtMfZ+Te0GiTy4CZZFybPjt5qpNrQrk8bi2BOjwYNwL7gJyMHKC7hPLfx6zYn+6aZAIR82egz+wIh/LS8cHWbHFNKT1Yj34sUaqt+7PTtLdI8o/rk98R/yd0vQEHFiNy//PLvzHp5OJ40LuT+pYrD9swpQAMBKVHr5pFZEInZga66CT4FdHKs1fpzOWpYm+wDUJ1bhgZAESz+ ZaMNG+wGIRwJeete7A3Qglo2i07wGfpqi6m0pEt4H07uw+4q5EEqRVJq+V/uPC18CcTvjrHq7zcawPhP+Q57bIWd2tqMkEv+RqOIDG7xKU2USlex5AeJ8vUDQ3wq7FpcWXb0h9X8afUMRWOck9R3X0QJnXRtQ3M+bRwncmJHvk0Nb5VhTQ2vlewFrUISZEXdeambirsj1x1AMksIbQCnzQoALB8pzjgmfde5sgw5oBWbIv1EKYxmPa+kOayiXxNrKTgfUTaPMfAbN27uF y1CqrpcRUAMLurTitnbavZlFvyCO+wcdP/tB8E0jIQ2juFAp/8RKMI6Mf0LsVOWzsFrjYwhq6Ehc0QvJI8adE0QuBlV1dMjFwg1KIHrvFeFlKPuSB2w1SIrN51wcohMfETbpj7NAYTLVKEzQo/3Wxc="
deploy:
  provider: pypi
  user: mirucha
  password:
    secure: "uSMbPGF+iSjhNALEse35mNFDP34kwHwDTA8QZefSaDMlHy/SphPbcmwp4BQpY/cgrP83kYDHssNsjexNVU4lqZZ4PbNU3LB/O+UHL4Vd/RgehC9MceRDmzTUXQ1V5nwRo+KO2K4u9mp6xv1HRtx+3auF7PIBYk5T/C3jb/kztjnbVIFVtcX9YB01xXftm3qmDi1JEmXqgiFuhMD7AGZjVU9y166EHT6TlHvWeOQUwN8wTtwd0NqRoeTTGEXUK0o1HI3fVxXH5bGaVHk+xHuA6tUr8PLJHPV1rS39lwolfpfKWPX9OMmo43r7E8gZ37jUMWHRnPj/iBoJq344s9gtmyN8QEEfC9QCbE7X4vafccisLVI+F2c6leXTn1WrVLfJNp7opDhf2d6Q8n0uHP8/xL6bW+p1XZNT0qF0U57xRMaxpPqFM8sZvck8zKT4IFYS3mdUiSCZGXC3lakcuaO+ASquMHH9DY/2FSU9X0+t3tBrSQB53AUCSOblR3QIpOkinpJoPAPc9hmg+23rz4HxLAC4zkoOmZdpoZfRrP1V9TdYWMfnvSzrv/YoskzaQP0sZuAzkj7b/FelyCJ9BuYWLCF3jqQfSjeKlyx3C2Gf66GPWOspxWCR6MB6KN630k22YzDJqqZM1zxetxUjq/Lyvs0BQqeWbH9aHRJFd4l7iBs="
  on:
    tags: true
    branch: master
script:
  - tox
after_success:
  - coveralls
