# Interface GigabitEthernet2, changed state to administratively down

messages:
  - error: INTERFACE_DOWN
    tag: LINEPROTO-5-UPDOWN
    values:
      interface: (\w+[\.\-\d\/\w+]+)
      adminStatus|upper: (\w+)
    line: 'Line protocol on Interface {interface}, changed state to down'
    model: openconfig-interfaces
    mapping:
      variables: {}
      static:
        interfaces//interface//{interface}//state//oper_status: DOWN
