# Line protocol on Interface FastEthernet0/2, changed state to down
messages:
  - error: INTERFACE_DOWN
    tag: LINEPROTO-5-UPDOWN
    values:
      interface: (\w+[\.\-\d\/\w+]+)
    line: 'Line protocol on Interface {interface}, changed state to down'
    model: openconfig-interfaces
    mapping:
      static:
        interfaces//interface//{interface}//state//oper_status: DOWN
      variables: {}
