#<30>ztp-tankstelle_1-ts port02 2018-Nov- 9 15:38:25.341 RXDATA: tankstelle_1-port2-dev#

messages:
  - error: RXDATA
    tag: RXDATA
    values:
      console_message: (.*)
    line: '{console_message}'
    model: NO_MODEL
    mapping:
      static:
        data: received
      variables: {}